"""Generate the Python SDK API reference page from the lightpanda package.

The hand-written src/content/reference/python.mdx explains how the package fits
together; this script writes the exhaustive companion page,
src/content/reference/python-api.mdx, by walking the installed `lightpanda`
package with pdoc's Python API and emitting one MDX section per public class,
method, property, function and exception, with the signatures and docstrings
shipped in the code. Emitting MDX instead of pdoc's own HTML keeps the page
inside the Nextra site: sidebar, search, dark mode and deep links all work as
on any other page.

Run it with the package installed from its main branch (that is what the
python-reference workflow does daily):

    uv run --no-project --python 3.13 --with 'pdoc==16.0.0' \\
      --with 'git+https://github.com/lightpanda-io/lightpanda-python' \\
      python scripts/generate-python-reference.py

The output is deterministic for a given package, Python and pdoc version, so
the workflow can detect changes with `git status`.
"""

from __future__ import annotations

import argparse
import inspect
import re
import sys
from pathlib import Path

import pdoc.doc
import pdoc.docstrings

import lightpanda

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = ROOT / "src" / "content" / "reference" / "python-api.mdx"

FRONTMATTER = """---
title: Python SDK
description: Reference of every public class, method, property and exception in the lightpanda Python package, generated from the signatures and docstrings shipped in the code.
---
"""

BANNER = (
    "{/* Generated by scripts/generate-python-reference.py from lightpanda-python main. "
    "Do not edit; rerun the script or wait for the python-reference workflow. */}"
)

INTRO = (
    "Every public class, method, property and exception of the "
    "[`lightpanda` package](https://pypi.org/project/lightpanda/), with the signatures and "
    "docstrings shipped in the code. See [Use the Python SDK](/guides/use-python) for a "
    "practical walkthrough. Every sync class has an asyncio twin with the same methods, "
    "awaitable; the async sections below list only what the twin adds."
)

CONVENTIONS = (
    "Browser actions are keyword-only methods on [`Session`](#session) and "
    "[`AsyncSession`](#asyncsession), named in snake_case after the browser's own action "
    "names: the `waitForSelector` action is `wait_for_selector`, and its `backendNodeId` "
    "argument is `backend_node_id`. Where a method accepts both `selector` and "
    "`backend_node_id`, pass one of the two; `selector` is preferred for reproducibility and "
    "wins when both are given, and `backend_node_id` takes the values returned by "
    "[`tree`](#session-tree), [`links`](#session-links) or "
    "[`find_element`](#session-find-element). [`Session.call`](#session-call) is the escape "
    "hatch that takes the action and argument names exactly as the browser declares them. "
    "A failed action raises [`ToolError`](#toolerror)."
)

FENCE_RE = re.compile(r"^\s*```")
CODE_SPAN_RE = re.compile(r"(`+)(.+?)\1", re.DOTALL)
MODULE_PREFIX_RE = re.compile(r"\blightpanda\.\w+\.")
LINK_RE = re.compile(r"\]\(#([a-z0-9-]+)\)")


def slug(*parts: str) -> str:
    return "-".join(p.lower().replace("_", "-") for p in parts)


def clean_signature(text: str) -> str:
    text = MODULE_PREFIX_RE.sub("", text)
    text = text.replace("typing.", "")
    return text


class Page:
    def __init__(self) -> None:
        self.lines: list[str] = []
        self.ids: set[str] = set()

    def heading(self, level: int, text: str, anchor: str) -> None:
        if anchor in self.ids:
            sys.exit(f"duplicate heading id: {anchor}")
        self.ids.add(anchor)
        self.lines.append(f"{'#' * level} {text} [#{anchor}]")
        self.lines.append("")

    def para(self, text: str) -> None:
        if text.strip():
            self.lines.append(text.rstrip())
            self.lines.append("")

    def fence(self, code: str, lang: str = "python") -> None:
        self.lines.append(f"```{lang}")
        self.lines.append(code.rstrip())
        self.lines.append("```")
        self.lines.append("")

    def text(self) -> str:
        text = "\n".join(self.lines).rstrip() + "\n"
        missing = sorted(set(LINK_RE.findall(text)) - self.ids)
        if missing:
            sys.exit(f"links to missing heading ids: {', '.join(missing)}")
        return text


# --- docstrings -------------------------------------------------------------


def fence_indented_blocks(text: str) -> str:
    """Wrap runs of indented lines (outside fences) in a text fence.

    Some docstrings carry hand-aligned tables, such as the value shapes of
    `extract`; markdown would fold them into the preceding paragraph.
    """
    out: list[str] = []
    block: list[str] = []
    in_fence = False

    def flush() -> None:
        if block:
            indent = min(len(line) - len(line.lstrip()) for line in block)
            if out and out[-1].strip():
                out.append("")
            out.append("```text")
            out.extend(line[indent:] for line in block)
            out.append("```")
            out.append("")
            block.clear()

    for line in text.split("\n"):
        if FENCE_RE.match(line):
            flush()
            in_fence = not in_fence
            out.append(line)
        elif not in_fence and line.startswith("  ") and line.strip():
            block.append(line.rstrip())
        else:
            flush()
            out.append(line)
    flush()
    return "\n".join(out)


def escape_prose(text: str) -> str:
    return text.replace("<", "&lt;").replace("{", "\\{").replace("}", "\\}")


def render_prose(text: str, links: dict[str, str]) -> str:
    """Escape MDX-significant characters outside inline code, link known symbols."""
    out: list[str] = []
    pos = 0
    for match in CODE_SPAN_RE.finditer(text):
        out.append(escape_prose(text[pos : match.start()]))
        span = match.group(0)
        target = links.get(match.group(2).removesuffix("()"))
        out.append(f"[{span}](#{target})" if target else span)
        pos = match.end()
    out.append(escape_prose(text[pos:]))
    return "".join(out)


def render_docstring(doc: pdoc.doc.Doc, links: dict[str, str]) -> str:
    raw = doc.docstring
    if not raw.strip():
        return ""
    text = pdoc.docstrings.convert(raw, "restructuredtext", doc.source_file)
    text = fence_indented_blocks(text)
    out: list[str] = []
    prose: list[str] = []
    in_fence = False

    def flush() -> None:
        if prose:
            out.append(render_prose("\n".join(prose), links))
            prose.clear()

    for line in text.split("\n"):
        if FENCE_RE.match(line):
            flush()
            in_fence = not in_fence
            out.append(line)
        elif in_fence:
            out.append(line)
        else:
            prose.append(line)
    flush()
    return "\n".join(out).strip()


# --- members ---------------------------------------------------------------


def is_public(member: pdoc.doc.Doc) -> bool:
    if member.name.startswith("_"):
        return False
    if isinstance(member, pdoc.doc.Function) and member.obj.__name__ != member.name:
        return False  # alias of another method
    return True


def public_members(cls: pdoc.doc.Class) -> list[pdoc.doc.Doc]:
    return [m for m in cls.members.values() if is_public(m)]


def param_names(func: pdoc.doc.Function) -> list[str]:
    return list(func.signature.parameters)


def twin_of(module: pdoc.doc.Module, cls: pdoc.doc.Class) -> pdoc.doc.Class | None:
    """The sync class an `Async*` class mirrors, when both are public."""
    name = cls.name.removeprefix("Async")
    twin = module.members.get(name) if name != cls.name else None
    return twin if isinstance(twin, pdoc.doc.Class) else None


def listed_members(module: pdoc.doc.Module, cls: pdoc.doc.Class) -> list[pdoc.doc.Doc]:
    """The members that get their own section: all of them, or for an async
    twin only those the sync class lacks or spells with different parameters."""
    members = public_members(cls)
    twin = twin_of(module, cls)
    if twin is None:
        return members
    twin_members = {m.name: m for m in public_members(twin)}

    def added(member: pdoc.doc.Doc) -> bool:
        other = twin_members.get(member.name)
        if other is None:
            return True
        if isinstance(member, pdoc.doc.Function) and isinstance(other, pdoc.doc.Function):
            return param_names(member) != param_names(other)
        return False

    return [m for m in members if added(m)]


def member_anchor(module: pdoc.doc.Module, cls: pdoc.doc.Class, name: str) -> str | None:
    """Heading id for `cls.name`, falling back to the sync twin's section."""
    if any(m.name == name for m in listed_members(module, cls)):
        return slug(cls.name, name)
    twin = twin_of(module, cls)
    if twin is not None:
        return member_anchor(module, twin, name)
    return None


def function_code(func: pdoc.doc.Function, name: str | None = None) -> str:
    decorators = "".join(f"{d}\n" for d in func.decorators)
    signature = clean_signature(str(func.signature))
    return f"{decorators}{func.funcdef} {name or func.name}{signature}"


def variable_annotation(cls: pdoc.doc.Class, var: pdoc.doc.Variable) -> str:
    annotation = var.annotation_str.removeprefix(":").strip()
    if not annotation:
        attr = getattr(cls.obj, var.name, None)
        if isinstance(attr, property) and attr.fget is not None:
            returns = inspect.signature(attr.fget).return_annotation
            if returns is not inspect.Signature.empty:
                annotation = inspect.formatannotation(returns)
    return clean_signature(annotation)


def is_property(cls: pdoc.doc.Class, var: pdoc.doc.Variable) -> bool:
    return isinstance(getattr(cls.obj, var.name, None), property)


def emit_member(page: Page, cls: pdoc.doc.Class, member: pdoc.doc.Doc, links: dict[str, str]) -> None:
    page.heading(3, f"{cls.name}.{member.name}", slug(cls.name, member.name))
    doc = render_docstring(member, links)
    if isinstance(member, pdoc.doc.Function):
        page.fence(function_code(member))
        page.para(doc)
    elif isinstance(member, pdoc.doc.Variable):
        annotation = variable_annotation(cls, member)
        page.fence(f"{member.name}: {annotation}" if annotation else member.name)
        if is_property(cls, member):
            page.para(f"*Property.* {doc}".rstrip())
        else:
            page.para(doc)


def class_code(cls: pdoc.doc.Class) -> str:
    init = cls.members.get("__init__")
    if isinstance(init, pdoc.doc.Function) and "__init__" in vars(cls.obj):
        return f"class {cls.name}{clean_signature(str(init.signature_without_self))}"
    return f"class {cls.name}"


def emit_class(page: Page, module: pdoc.doc.Module, cls: pdoc.doc.Class, links: dict[str, str]) -> None:
    page.heading(2, cls.name, slug(cls.name))
    page.para(render_docstring(cls, links))
    page.fence(class_code(cls))
    init = cls.members.get("__init__")
    if isinstance(init, pdoc.doc.Function) and "__init__" in vars(cls.obj):
        page.para(render_docstring(init, links))
    managers = []
    if "__enter__" in cls.members:
        managers.append("`with`")
    if "__aenter__" in cls.members:
        managers.append("`async with`")
    if managers:
        page.para(f"Usable as a context manager ({' and '.join(managers)}).")

    members = listed_members(module, cls)
    twin = twin_of(module, cls)
    if twin is not None:
        page.para(
            f"Every public method and property of [`{twin.name}`](#{slug(twin.name)}) exists on "
            f"`{cls.name}` with the same name and signature; methods are coroutines to `await`. "
            + (
                f"Only the members `{cls.name}` adds are listed below."
                if members
                else f"`{cls.name}` adds no members of its own."
            )
        )
    for member in members:
        emit_member(page, cls, member, links)


def emit_function(page: Page, func: pdoc.doc.Function, links: dict[str, str]) -> None:
    page.heading(2, func.name, slug(func.name))
    page.fence(function_code(func))
    page.para(render_docstring(func, links))


def emit_exception(page: Page, cls: pdoc.doc.Class, links: dict[str, str]) -> None:
    page.heading(3, cls.name, slug(cls.name))
    bases = [name for _, name, qualname in cls.bases if qualname != "builtins.object"]
    code = f"class {cls.name}({', '.join(bases)})" if bases else f"class {cls.name}"
    init = cls.members.get("__init__")
    if isinstance(init, pdoc.doc.Function) and "__init__" in vars(cls.obj):
        code += f"\n{cls.name}{clean_signature(str(init.signature_without_self))}"
    page.fence(code)
    page.para(render_docstring(cls, links))
    attrs = [m for m in cls.own_members if isinstance(m, pdoc.doc.Variable) and is_public(m)]
    if attrs:
        for attr in attrs:
            annotation = variable_annotation(cls, attr)
            line = f"- `{attr.name}`" + (f": `{annotation}`" if annotation else "")
            doc = render_docstring(attr, links)
            if doc:
                line += f". {doc}"
            page.lines.append(line)
        page.lines.append("")


# --- page ------------------------------------------------------------------


def collect_links(module: pdoc.doc.Module, names: list[str]) -> dict[str, str]:
    """Map symbol spellings found in docstrings to heading ids."""
    links: dict[str, str] = {}
    for name in names:
        doc = module.members[name]
        links[name] = slug(name)
        if isinstance(doc, pdoc.doc.Class):
            for member in public_members(doc):
                anchor = member_anchor(module, doc, member.name)
                if anchor:
                    links[f"{name}.{member.name}"] = anchor
    return links


def class_links(
    module: pdoc.doc.Module, links: dict[str, str], cls: pdoc.doc.Class
) -> dict[str, str]:
    """Resolve bare member names (`start()`) against the class being rendered."""
    scoped = dict(links)
    for member in public_members(cls):
        anchor = member_anchor(module, cls, member.name)
        if anchor:
            scoped.setdefault(member.name, anchor)
    return scoped


def generate() -> str:
    module = pdoc.doc.Module(lightpanda)
    names = [n for n in lightpanda.__all__ if n in module.members]
    links = collect_links(module, names)
    page = Page()

    page.lines.append(FRONTMATTER.rstrip())
    page.lines.append(BANNER)
    page.lines.append("")
    page.lines.append("# Python SDK")
    page.lines.append("")
    page.para(INTRO)
    page.para(CONVENTIONS)
    page.para(render_docstring(module, links))

    exceptions: list[pdoc.doc.Class] = []
    for name in names:
        doc = module.members[name]
        if isinstance(doc, pdoc.doc.Class):
            if issubclass(doc.obj, BaseException):
                exceptions.append(doc)
            else:
                emit_class(page, module, doc, class_links(module, links, doc))
        elif isinstance(doc, pdoc.doc.Function):
            emit_function(page, doc, links)

    if exceptions:
        page.heading(2, "Exceptions", "exceptions")
        for doc in exceptions:
            emit_exception(page, doc, class_links(module, links, doc))

    return page.text()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="output .mdx path")
    args = parser.parse_args()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(generate(), encoding="utf-8", newline="\n")
    print(f"wrote {args.out.relative_to(ROOT) if args.out.is_relative_to(ROOT) else args.out}")


if __name__ == "__main__":
    main()
